### ISSUE TITLE
.hy files do not indent correctly with hy==0.12.0

### ISSUE THREAD

**Issue by chr15m** [hylang/vim-hy#13]
Neither auto-indenting nor indenting a block seem to do anything with `hy==0.12.0` installed.

**Comment by OwenChia** [comment]
I have the same problems as you.

**Comment by kirbyfan64** [comment]
FWIW at this point I think you guys would be better off using a Clojure mode and setting it to be used on `.hy`.

**Comment by vilmibm** [comment]
this is working now afaict

**Comment by iamtuxmeister** [comment]
I ripped off this plugin, and the Clojure indent from vim-clojure-static and merged them. it is not on https://github.com/iamtuxmeister/vim-hy/ someone feel free to rip it off, and start maintaining this again.
