### ISSUE TITLE
Macro Expansion error on hy file load

### ISSUE THREAD

**Issue by silver-dragon** [hylang/vim-hy#26]
On loading a .Hy file with the vim-hy plugin I get a macro expansion error.

In the hy_indent.hy file

![image](https://user-images.githubusercontent.com/20142273/118889252-b3c9c880-b8b1-11eb-8a0c-42042e2593f7.png)

**Comment by scauligi** [comment]
I just merged #25 which should remove using Hy itself to do the indent calculation, should be good now!
