### ISSUE TITLE
conceal makes some some characters unreadable

### ISSUE THREAD

**Issue by silver-dragon** [hylang/vim-hy#27]
Not sure if this is a vim bug or a or a issue with the plugin. However the characters that are concealed become unreadable due to the color change after being concealed. I have tried this out with many different color schemes with mostly the same results. 

![Screenshot from 2021-05-26 09-52-45](https://user-images.githubusercontent.com/20142273/119700889-9f815080-be08-11eb-8e3d-8b55471557d0.png)

The one work around I was able to figure out was to run this command after starting vim and it will change the concealment characters back to the default terminal colors in my case white. I tried adding this to both the theme and the my vimrc and wasn't able to make the change happen on startup. 

`:highlight Conceal ctermbg=NONE ctermfg=NONE guibg=NONE guifg=NONE`

**Comment by silver-dragon** [comment]
I am trying to replicate this issue on my other workstation now and I am unable to I have a suspicion that it may be another plugin that is conflicting. This workstation has a different vim config than the other one, I will try systematically disabling plugins until I can figure out what's conflicting.

**Comment by silver-dragon** [comment]
It appears the plugin `Yggdroot/indentLine` was overwriting the conceal highlight with a dark color.

**Comment by aselker** [comment]
I had the same issue, and adding `highlight Conceal ctermbg=NONE ctermfg=NONE guibg=NONE guifg=NONE` fixed it for me.
