### ISSUE TITLE
Add syntax highlighting for let and other alpha-release builtin keywords

### ISSUE THREAD

**Issue by caligian** [hylang/vim-hy#28]
Syntax highlighting is missing for `(let [...] ...)`. Can you add syntax highlighting for other similar macros covered under alpha release?

**Comment by scauligi** [comment]
Should be fixed with https://github.com/hylang/vim-hy/commit/813ff051dfc73ed225ef71495c2b235f84fbaa1e, thanks for opening an issue!

Let me know if there are any keywords I missed.
