### ISSUE TITLE
Fix default conceal for xi forms

### ISSUE THREAD

**Issue by gilch** [hylang/vim-hy#8]
Currently it's using `xⁱ ; x₀ - x₉`. The reason for the `xⁱ` instead of `xᵢ` is that U+1D62 in unavailable in many programming fonts, though it is in Consolas, for example. So now we're mixing superscripts with subscripts.

A better default might be `x¡` with `x₀ - x₉`. This is "U+001A: Inverted Exclamation Mark". It resembles the desired subscript i pretty closely and it's in pretty much every font.

A possible alternative is all superscripts:
`xⁱ ; x⁰ - x⁹`.
This kind of looks like a polynomial, so subscripts are better defaults. You could write them in the opposite order to make them look less like exponents:
`ⁱx ; ⁰x - ⁹x`.

`⁴⁵⁶⁷⁸⁹` are U+2074 through U+2079. `²`,`³`, `¹`, and `⁰` are U+00B2, U+00B3, U+00B9, and U+2070, respectively.

**Comment by farhaven** [comment]
I went with the first suggestion, polinomial-style superscripts were just too confusing :smile:
